const mongoose = require("mongoose");

const helpCookingSchema = new mongoose.Schema({
  location: String,
  dayHelpCooking: Date,
});

const achievementSchema = new mongoose.Schema({
  semester: Number,
  schoolYear: String,
  content: String,
});

const tuitionFeeSchema = new mongoose.Schema({
  totalAmount: String,
  semester: String,
  content: String,
  status: String,
});

const physicalResultSchema = new mongoose.Schema({
  semester: String,
  run3000m: String,
  run100m: String,
  pullUpBar: Number,
  swimming100m: String,
  practise: String,
});

const learningInformationSchema = new mongoose.Schema({
  semester: String,
  CPA: Number,
  GPA: Number,
  cumulativeCredit: Number,
  studentLevel: Number,
  warningLevel: Number,
  totalDebt: Number,
  learningStatus: String,
});

// Schema cho kết quả học tập chi tiết theo từng môn học
const subjectResultSchema = new mongoose.Schema({
  subjectCode: { type: String, required: true }, // Mã môn học
  subjectName: { type: String, required: true }, // Tên môn học
  credits: { type: Number, required: true }, // Số tín chỉ
  letterGrade: {
    type: String,
    enum: ["A+", "A", "B+", "B", "C+", "C", "D+", "D", "F"],
    required: true,
  }, // Điểm chữ
  gradePoint4: { type: Number, required: true }, // Điểm hệ 4
  gradePoint10: { type: Number, required: true }, // Điểm hệ 10
});

// Schema cho kết quả học tập theo học kỳ
const semesterResultSchema = new mongoose.Schema({
  semester: { type: Number, required: true }, // Học kỳ (1 hoặc 2)
  schoolYear: { type: String, required: true }, // Năm học
  subjects: [subjectResultSchema], // Danh sách môn học
  totalCredits: { type: Number, default: 0 }, // Tổng số tín chỉ
  averageGrade4: { type: Number, default: 0 }, // Điểm trung bình hệ 4
  averageGrade10: { type: Number, default: 0 }, // Điểm trung bình hệ 10
  cumulativeCredits: { type: Number, default: 0 }, // Tổng tín chỉ tích lũy
  cumulativeGrade4: { type: Number, default: 0 }, // Điểm tích lũy hệ 4
  cumulativeGrade10: { type: Number, default: 0 }, // Điểm tích lũy hệ 10
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

const cutRiceSchema = new mongoose.Schema({
  monday: {
    breakfast: Boolean,
    lunch: Boolean,
    dinner: Boolean,
  },
  tuesday: {
    breakfast: Boolean,
    lunch: Boolean,
    dinner: Boolean,
  },
  wednesday: {
    breakfast: Boolean,
    lunch: Boolean,
    dinner: Boolean,
  },
  thursday: {
    breakfast: Boolean,
    lunch: Boolean,
    dinner: Boolean,
  },
  friday: {
    breakfast: Boolean,
    lunch: Boolean,
    dinner: Boolean,
  },
  saturday: {
    breakfast: Boolean,
    lunch: Boolean,
    dinner: Boolean,
  },
  sunday: {
    breakfast: Boolean,
    lunch: Boolean,
    dinner: Boolean,
  },
  // Thông tin về lịch cắt cơm
  isAutoGenerated: {
    type: Boolean,
    default: true,
  },
  lastUpdated: {
    type: Date,
    default: Date.now,
  },
  notes: String,
});

const studentSchema = mongoose.model(
  "Student",
  new mongoose.Schema({
    studentId: { type: String, unique: true },
    fullName: { type: String, unique: true },
    gender: String,
    birthday: Date,
    hometown: String,
    currentAddress: String, // Nơi ở hiện nay
    email: String,
    phoneNumber: String,
    enrollment: Number,
    university: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "University",
    },
    organization: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
    },
    educationLevel: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "education_level",
    },
    class: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Class",
    },

    unit: String,
    rank: String,
    positionGovernment: String,
    positionParty: String,
    fullPartyMember: Date,
    probationaryPartyMember: Date,
    dateOfEnlistment: Date,
    avatar: {
      type: String,
      default:
        "https://i.pinimg.com/564x/24/21/85/242185eaef43192fc3f9646932fe3b46.jpg",
    },
    timeTable: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "time_table",
      },
    ],
    violation: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Violation",
      },
    ],
    vacationSchedule: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "vacation_schedule",
      },
    ],
    helpCooking: [helpCookingSchema],
    achievement: [achievementSchema],
    tuitionFee: [tuitionFeeSchema],
    physicalResult: [physicalResultSchema],
    learningInformation: [learningInformationSchema],
    semesterResults: [semesterResultSchema], // Kết quả học tập theo học kỳ
    cutRice: [cutRiceSchema],
  })
);

module.exports = studentSchema;
